// <auto-generated />
using System;
using MatchTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MatchTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730024322_AddPlacarToPartida")]
    partial class AddPlacarToPartida
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MatchTracker.Api.Entities.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Assistencias")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DataPartida")
                        .HasColumnType("date");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("Mapa")
                        .HasColumnType("integer");

                    b.Property<int>("Mortes")
                        .HasColumnType("integer");

                    b.Property<int>("PlacarAdversario")
                        .HasColumnType("integer");

                    b.Property<int>("PlacarTime")
                        .HasColumnType("integer");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });
#pragma warning restore 612, 618
        }
    }
}
